name: Terraform Deploy on Push

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      IMAGE_TAG: ${{ github.sha }}
      TF_ENV: ${{ github.ref_name }}
      ECR_REPO_NAME: ${{ github.ref_name == 'dev' && 'devpython' || github.ref_name == 'stage' && 'stagepython' || 'prodpython' }}
      TF_DIR: ${{ github.ref_name == 'dev' && 'modules/DevECS' || github.ref_name == 'stage' && 'modules/StageECS' || 'modules/ProdECS' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan
        run: |
          terraform plan \
          -var="image_tag=${{ env.IMAGE_TAG }}" \
          -var="ecr_repo_name=${{ env.ECR_REPO_NAME }}" \
          -var="environment=${{ env.TF_ENV }}" \
          -out=tfplan
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Destroy
        run: |
            terraform destroy -auto-approve \
            -var="image_tag=${{ env.IMAGE_TAG }}" \
             -var="ecr_repo_name=${{ env.ECR_REPO_NAME }}" \
             -var="environment=${{ env.TF_ENV }}"
             working-directory: ${{ env.TF_DIR }}



