name: Build and Push to ECR

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Environment Variables
        
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [[ "$BRANCH" == "dev" ]]; then
            REPO_NAME="devpython"
            CONTAINER_NAME="dev-container"
          elif [[ "$BRANCH" == "stage" ]]; then
            REPO_NAME="stagepython"
            CONTAINER_NAME="stage-container"
          else
            REPO_NAME="mainpython"
            CONTAINER_NAME="main-container"
          fi
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:$IMAGE_TAG"

          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_URI .

      - name: Push Docker Image to ECR
        run: |
          docker push $IMAGE_URI

      - name: Write imagedefinitions.json
        run: |
          echo '[{"name":"'"$CONTAINER_NAME"'","imageUri":"'"$IMAGE_URI"'"}]' > imagedefinitions.json
          cat imagedefinitions.json

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: imagedefinitions
          path: imagedefinitions.json
