name: Terraform Deployment

on:
  push:
    branches:
      - "*"  

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}  

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Terraform Init - ECS
        run: terraform init
        working-directory: modules/DevECS

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: modules/DevECS

      #- name: Terraform Apply - ECS (after approval)
       # run: terraform apply -auto-approve tfplan
       # working-directory: modules/DevECS

      # Optional: Destroy step
      # - name: Destroy Terraform
      #   run: terraform destroy -auto-approve
      #   working-directory: modules/ECS
