name: Terraform Dev Deployment

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "Set to true to destroy infrastructure"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: modules/dev

      - name: Terraform Plan
        if: ${{ github.event.inputs.destroy != 'true' }}
        run: terraform plan -out=tfplan
        working-directory: modules/dev

      - name: Terraform Apply
        if: ${{ github.event.inputs.destroy != 'true' }}
        run: terraform apply -auto-approve tfplan
        working-directory: modules/dev

      - name: Terraform Destroy
        if: ${{ github.event.inputs.destroy == 'true' }}
        run: terraform destroy -auto-approve
        working-directory: modules/dev
