name: Terraform Deployment

on:
  push:
    branches:
      - dev
      - stage
      - main

env:
  AWS_REGION: us-east-1

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            path: repo

      - name: Set ENV Directory
        id: setdir
        run: |
          DIR_NAME="${GITHUB_REF_NAME}ECS"
          echo "DIR_NAME=$DIR_NAME" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: repo/modules/${{ env.DIR_NAME }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: repo/modules/${{ env.DIR_NAME }}

      - name: Upload tfplan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: modules/${{ env.DIR_NAME }}/tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           path: repo

      - name: Set ENV Directory
        id: setdir
        run: |
          DIR_NAME="${GITHUB_REF_NAME}ECS"
          echo "DIR_NAME=$DIR_NAME" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Download tfplan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: modules/${{ env.DIR_NAME }}

      - name: Terraform Init
        run: terraform init
        working-directory: repo/modules/${{ env.DIR_NAME }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: repo/modules/${{ env.DIR_NAME }}
