name: Terraform Deployment

on:
  push:
    branches:
      - stage

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # VPC first
      - name: Terraform Init - VPC
        run: terraform init
        working-directory: modules/VPC

      - name: Terraform Apply - VPC
        run: terraform apply -auto-approve
        working-directory: modules/VPC

      - name: Destroy Terraform
        run: terraform destroy -auto-approve
        working-directory: modules/VPC

      # ECS second (after VPC is ready)
      - name: Terraform Init - ECS
        run: terraform init
        working-directory: modules/ECS

      - name: Terraform Apply - ECS
        run: terraform apply -auto-approve
        working-directory: modules/ECS

      - name: Destroy Terraform
        run: terraform destroy -auto-approve
        working-directory: modules/ECS
