name: Terraform Deployment

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      image_url:
        description: 'ECR image URL to deploy'
        required: true
        type: string
      target_branch:
        description: 'Branch to deploy'
        required: true
        type: string
      env_name:
        description: 'Deployment environment (e.g., dev, stage, prod)'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init - ECS
        run: terraform init
        working-directory: modules/ECS

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var="image_uri=${{ github.event.inputs.image_url }}"
        working-directory: modules/ECS

      - name: Terraform Apply - ECS
        run: terraform apply -auto-approve -var="image_uri=${{ github.event.inputs.image_url }}"
        working-directory: modules/ECS
