name: Terraform Deployment

on:
  push:
    branches:
      - dev
      

  workflow_dispatch:
    inputs:
      destroy:
        description: "Set to true to run terraform destroy"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true' && 'Terraform Destroy' || 'Terraform Apply' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: modules/ECS

      - name: Terraform Plan (on push or if destroy is false)
        if: ${{ github.event_name == 'push' || github.event.inputs.destroy != 'true' }}
        run: terraform plan -out=tfplan
        working-directory: modules/ECS

      - name: Terraform Apply (on push or if destroy is false)
        if: ${{ github.event_name == 'push' || github.event.inputs.destroy != 'true' }}
        run: terraform apply -auto-approve tfplan
        working-directory: modules/ECS

      - name: Terraform Destroy (only if manual and destroy=true)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true' }}
        run: terraform destroy -auto-approve
        working-directory: modules/ECS
