name: Terraform Deployment

on:
  push:
    branches:
      - stage

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2        # clone to the repo

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Initialize Terraform
        run: terraform init
        working-directory: Modules

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: Modules

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
        working-directory: Modules

      #- name: Destroy Terraform
       # run: terraform destroy -auto-approve
        #working-directory: Modules
        

       


        
