name: Terraform Deploy

on:
  repository_dispatch:
    types: [deploy-dev, deploy-stage, deploy-main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
      ECR_REPO_NAME: ${{ github.event.client_payload.ecr_repo_name }}
      ENVIRONMENT: ${{ github.event.client_payload.environment }}

    steps:
      - name: Print GitHub Event
        run: echo "${{ toJson(github.event) }}"

      - name: Checkout Infra Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: modules/DevECS

      - name: Terraform Plan
        run: terraform plan \
          -var="image_tag=${{ env.IMAGE_TAG }}" \
          -var="ecr_repo_name=${{ env.ECR_REPO_NAME }}" \
          -var="environment=${{ env.ENVIRONMENT }}" \
          -var="aws_region=${{ env.AWS_REGION }}"
        working-directory: modules/DevECS

      #- name: Terraform Apply
       # run: terraform apply -auto-approve \
        #  -var="image_tag=${{ env.IMAGE_TAG }}" \
         # -var="ecr_repo_name=${{ env.ECR_REPO_NAME }}" \
          #-var="environment=${{ env.ENVIRONMENT }}" \
          #-var="aws_region=${{ env.AWS_REGION }}"
       # working-directory: modules/DevECS
